#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py:twisted
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class slim_errors:
  ok = 0
  gen_server_internal = 100001
  gen_bad_request = 100002
  gen_partial_completed = 100003
  gen_permission_denied = 100004
  gen_exceed_request_limit = 100005
  gen_ip_banned = 100006
  err_user_exists = 110001
  reg_too_much_reg_in_current_loc = 110002
  err_token_invalid = 110003
  err_token_expired = 110004
  err_user_inactive = 110005
  err_bad_token = 110006
  err_user_banned = 110007
  err_user_activated = 110008
  err_user_pending_email_validation = 110009
  gen_need_authentication = 110065
  auth_invalid_user_or_pass = 110066
  auth_too_much_errors = 110067
  auth_invalid_account_status = 110068
  auth_permission_denied = 110069
  auth_invalid_token = 120001
  auth_invalid_credential = 120002
  auth_invalid_terminal_id = 120003
  auth_unsupported_terminal_type = 120004
  auth_unsupported_OS_type = 120005
  rpc_server_not_available = 500001
  rpc_server_suspended = 500002
  rpc_client_bad_routing = 500003
  rpc_server_timeout = 500004
  rpc_server_internal = 500005
  server_too_much_users = 880001
  server_not_implemented = 880002
  gen_client_version_expired = 990001
  gen_config_version_expired = 990002
  gen_protocol_not_supported = 990003
  nexus_invalid_license = 900001

  _VALUES_TO_NAMES = {
    0: "ok",
    100001: "gen_server_internal",
    100002: "gen_bad_request",
    100003: "gen_partial_completed",
    100004: "gen_permission_denied",
    100005: "gen_exceed_request_limit",
    100006: "gen_ip_banned",
    110001: "err_user_exists",
    110002: "reg_too_much_reg_in_current_loc",
    110003: "err_token_invalid",
    110004: "err_token_expired",
    110005: "err_user_inactive",
    110006: "err_bad_token",
    110007: "err_user_banned",
    110008: "err_user_activated",
    110009: "err_user_pending_email_validation",
    110065: "gen_need_authentication",
    110066: "auth_invalid_user_or_pass",
    110067: "auth_too_much_errors",
    110068: "auth_invalid_account_status",
    110069: "auth_permission_denied",
    120001: "auth_invalid_token",
    120002: "auth_invalid_credential",
    120003: "auth_invalid_terminal_id",
    120004: "auth_unsupported_terminal_type",
    120005: "auth_unsupported_OS_type",
    500001: "rpc_server_not_available",
    500002: "rpc_server_suspended",
    500003: "rpc_client_bad_routing",
    500004: "rpc_server_timeout",
    500005: "rpc_server_internal",
    880001: "server_too_much_users",
    880002: "server_not_implemented",
    990001: "gen_client_version_expired",
    990002: "gen_config_version_expired",
    990003: "gen_protocol_not_supported",
    900001: "nexus_invalid_license",
  }

  _NAMES_TO_VALUES = {
    "ok": 0,
    "gen_server_internal": 100001,
    "gen_bad_request": 100002,
    "gen_partial_completed": 100003,
    "gen_permission_denied": 100004,
    "gen_exceed_request_limit": 100005,
    "gen_ip_banned": 100006,
    "err_user_exists": 110001,
    "reg_too_much_reg_in_current_loc": 110002,
    "err_token_invalid": 110003,
    "err_token_expired": 110004,
    "err_user_inactive": 110005,
    "err_bad_token": 110006,
    "err_user_banned": 110007,
    "err_user_activated": 110008,
    "err_user_pending_email_validation": 110009,
    "gen_need_authentication": 110065,
    "auth_invalid_user_or_pass": 110066,
    "auth_too_much_errors": 110067,
    "auth_invalid_account_status": 110068,
    "auth_permission_denied": 110069,
    "auth_invalid_token": 120001,
    "auth_invalid_credential": 120002,
    "auth_invalid_terminal_id": 120003,
    "auth_unsupported_terminal_type": 120004,
    "auth_unsupported_OS_type": 120005,
    "rpc_server_not_available": 500001,
    "rpc_server_suspended": 500002,
    "rpc_client_bad_routing": 500003,
    "rpc_server_timeout": 500004,
    "rpc_server_internal": 500005,
    "server_too_much_users": 880001,
    "server_not_implemented": 880002,
    "gen_client_version_expired": 990001,
    "gen_config_version_expired": 990002,
    "gen_protocol_not_supported": 990003,
    "nexus_invalid_license": 900001,
  }

